using System.Numerics;
using System.Collections.Immutable;
using IslandRpg.Simulation;

namespace IslandRpg.Resources;

/// <summary>
/// Stable identity of a procedural resource. Empty is reserved for malformed
/// or absent wire values and is never produced by the identity service.
/// </summary>
public readonly record struct ResourceNodeId(Guid Value)
{
    public static ResourceNodeId Empty => default;

    public bool IsEmpty => Value == Guid.Empty;

    public override string ToString() => Value.ToString("N");
}

public enum ResourceNodeKind : byte
{
    Tree = 1,
    FibreShrub = 2,
    BerryBush = 3,
    MiningNode = 4,
    FishSchool = 5
}

public enum ResourceActionKind : byte
{
    CutTree = 1,
    GatherTreeStick = 2,
    GatherFibre = 3,
    GatherBerries = 4,
    Mine = 5,
    Fish = 6
}

/// <summary>
/// Client claim against one authoritative node version. The descriptor is
/// always regenerated by the authority; callers cannot supply its position,
/// variant, rewards or initial state.
/// </summary>
public readonly record struct ResourceNodeReference(
    ResourceNodeId Id,
    WorldChunkKey Chunk,
    uint ExpectedNodeRevision,
    uint ExpectedResourceChunkRevision)
{
    public bool IsWellFormed => !Id.IsEmpty;
}

/// <summary>
/// Immutable data regenerated from the world seed. Variant is a catalog-owned
/// numeric discriminator such as tree type, ore type or fish species.
/// </summary>
public sealed record ResourceNodeDescriptor(
    ResourceNodeId Id,
    ResourceNodeKind Kind,
    WorldChunkKey Chunk,
    Vector2 Position,
    int Variant,
    int InitialHealth = 0,
    int MaximumHealth = 0,
    int InitialRemaining = 0,
    double RegrowthGameSeconds = 0);

/// <summary>
/// Only values which differ from procedural defaults need persistence or
/// replication. Zero revisions are valid for a never-mutated default node.
/// </summary>
public sealed record ResourceNodeSparseState(
    ResourceNodeId Id,
    ResourceNodeKind Kind,
    WorldChunkKey Chunk,
    uint NodeRevision,
    int Health,
    int Remaining,
    double ReadyAtGameSeconds,
    bool Depleted);

/// <summary>
/// Durable/public sparse overlay for one procedural chunk. The procedural
/// catalog supplies omitted defaults; only mutated nodes occupy this array.
/// </summary>
public sealed record ResourceChunkSparseState(
    WorldChunkKey Chunk,
    uint ResourceChunkRevision,
    ImmutableArray<ResourceNodeSparseState> Nodes);

/// <summary>
/// Dependency-free cadence primitive. Gameplay policy supplies the canonical
/// interval; the server, never the client animation, owns ReadyAtSeconds.
/// </summary>
public readonly record struct ResourceActionCadence
{
    public ResourceActionCadence(double intervalSeconds)
    {
        if (!double.IsFinite(intervalSeconds) || intervalSeconds <= 0)
            throw new ArgumentOutOfRangeException(nameof(intervalSeconds));
        IntervalSeconds = intervalSeconds;
    }

    public double IntervalSeconds { get; }

    public bool IsReady(double nowSeconds, double readyAtSeconds)
    {
        EnsureInitialized();
        return double.IsFinite(nowSeconds) &&
               double.IsFinite(readyAtSeconds) &&
               nowSeconds >= readyAtSeconds;
    }

    public double NextReadyAt(double nowSeconds)
    {
        EnsureInitialized();
        if (!double.IsFinite(nowSeconds))
            throw new ArgumentOutOfRangeException(nameof(nowSeconds));
        var result = nowSeconds + IntervalSeconds;
        if (!double.IsFinite(result) || result <= nowSeconds)
            throw new ArgumentOutOfRangeException(nameof(nowSeconds));
        return result;
    }

    private void EnsureInitialized()
    {
        if (!double.IsFinite(IntervalSeconds) || IntervalSeconds <= 0)
        {
            throw new InvalidOperationException(
                "The resource action cadence is not initialized.");
        }
    }
}
