<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FontStashSharp.PlatformAgnostic" Version="1.5.6" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Fonts\Arimo-Variable.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Fonts\OFL-Arimo.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\woodcutting-items.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\rocks-sticks-items.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\seeds-materials-items.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\stone-tools-items.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\stone-pickaxe-item.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\coastal-collectibles.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Images\fish-items.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
